/**
 * ExportEngine
 * CANONICAL SOURCE — extracted verbatim from index.html lines 5684–6589
 * Do NOT edit this file without updating index.html placeholder comment.
 * Dependencies: ChartEngine, ExportDebug, SnapshotEngine, State (all inline, all lazy)
 * External libs: html2canvas (CDN), jsPDF via window.jspdf (CDN)
 * Load order: before inline <script> block
 * Wiring: NOT YET WIRED — extraction only
 */

/**
 * ExportEngine — Phase 1 v5 STABLE
 * All critical + high + medium validation fixes applied.
 * Depends on: html2canvas (global), jsPDF (window.jspdf)
 * Zero modifications to: KPIEngine, RenderEngine, ChartEngine, FilterEngine
 */
const ExportEngine = {

  // ── Config constants ─────────────────────────────────────────────────
  SCALE_PNG:   1.5,   // Full-page default (safe for large dashboards)
  SCALE_PDF:   1.2,
  PDF_MARGIN:  10,

  // ── Adaptive scale thresholds (section height → scale) ───────────────
  // Small  < 1200px → 3x   (CA, Action — ultra-sharp WhatsApp-ready)
  // Medium 1200–2500px → 2x (PS, WS-partial — very sharp)
  // Large  > 2500px → 1.5x  (Performance, WS-full — safe sharp)
  SCALE_SECTION_SMALL:  3.0,
  SCALE_SECTION_MEDIUM: 2.0,
  SCALE_SECTION_LARGE:  1.5,
  HEIGHT_SMALL:  1200,
  HEIGHT_MEDIUM: 2500,

  // ── Memory safety: max canvas area in megapixels before downgrade ─────
  MAX_CANVAS_MP:    64,    // 64MP = 8000x8000 — safe ceiling for all browsers
  SAFARI_CANVAS_MP: 16,    // Safari/iOS hard limit ~16MP (4096x4096)

  // ── State ─────────────────────────────────────────────────────────────
  _toastTimer:   null,
  _savedScrollY: 0,
  _isExporting:   false,  // mutex: prevents concurrent export
  _exportCount:   0,      // rolling counter for debug labeling
  _panelWasOpen:  false,  // saved pre-export state of anomaly-panel

  // ── Filename ────────────────────────────────────────────────────────
  _filename: (prefix, ext) => {
    const n = new Date();
    const d = `${n.getFullYear()}${String(n.getMonth()+1).padStart(2,'0')}${String(n.getDate()).padStart(2,'0')}`;
    const t = `${String(n.getHours()).padStart(2,'0')}${String(n.getMinutes()).padStart(2,'0')}`;
    return `${prefix}_${d}_${t}.${ext}`;
  },

  // ── Adaptive section scale: picks optimal scale from section height ───
  // Returns 3×, 2×, or 1.5× based on element height thresholds.
  // For full-page captures, pass the explicit SCALE_PNG constant instead.
  _adaptiveScale: (element) => {
    const h = element.getBoundingClientRect().height;
    if (h < ExportEngine.HEIGHT_SMALL)  return ExportEngine.SCALE_SECTION_SMALL;
    if (h < ExportEngine.HEIGHT_MEDIUM) return ExportEngine.SCALE_SECTION_MEDIUM;
    return ExportEngine.SCALE_SECTION_LARGE;
  },

  // ── Memory safety: checks estimated canvas MP before any capture ──────
  // Returns {safe:bool, scale:number, mp:number, warning:string|null}
  _memoryCheck: (element, requestedScale) => {
    const rect = element.getBoundingClientRect();
    const w    = rect.width  * requestedScale;
    const h    = rect.height * requestedScale;
    const mp   = (w * h) / 1_000_000;

    // Detect Safari/iOS for tighter limit
    const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
    const limitMp  = isSafari ? ExportEngine.SAFARI_CANVAS_MP : ExportEngine.MAX_CANVAS_MP;

    if (mp <= limitMp) {
      return { safe: true, scale: requestedScale, mp, warning: null };
    }

    // Downgrade scale to fit within limit
    const area    = rect.width * rect.height;
    const maxPx   = limitMp * 1_000_000;
    const ratio   = Math.sqrt(maxPx / area);
    const safe    = Math.max(1.0, Math.floor(ratio * 10) / 10);
    const safeMp  = (rect.width * safe * rect.height * safe) / 1_000_000;
    const warning = `Canvas ${mp.toFixed(1)}MP exceeds ${isSafari?'Safari':'browser'} limit (${limitMp}MP). Auto-reduced to ${safe}×`;

    console.warn(`[ExportEngine._memoryCheck] ${warning}`);
    ExportDebug.set('risk', `${mp.toFixed(1)}MP → ${safe}× (limit: ${limitMp}MP)`, 'warn');

    return { safe: false, scale: safe, mp: safeMp, warning };
  },

  // ── Combined scale resolver: adaptive + memory safe ──────────────────
  // Use this instead of _safeScale for all section exports.
  // For full-page, pass explicit scale and use _memoryCheck only.
  _resolveScale: (element, hintScale) => {
    const scale  = hintScale ?? ExportEngine._adaptiveScale(element);
    const check  = ExportEngine._memoryCheck(element, scale);
    if (!check.safe) {
      ExportEngine._toast(`Quality adjusted: ${check.warning}`, 'info', 4000);
    }
    ExportDebug.set('scale', `${check.scale}× (${check.mp.toFixed(1)}MP)`, check.safe ? 'info' : 'warn');
    return check.scale;
  },

  // ── Legacy alias (keeps existing fullPNG / fullPDF calls working) ─────
  _safeScale: (element, requestedScale) => {
    return ExportEngine._resolveScale(element, requestedScale);
  },

  // ── Overlay helpers ──────────────────────────────────────────────────
  _showOverlay: (title, sub, pct = 0) => {
    const o = document.getElementById('export-overlay');
    const t = document.getElementById('export-overlay-title');
    const s = document.getElementById('export-overlay-sub');
    const b = document.getElementById('export-overlay-bar');
    if (t) t.textContent = title;
    if (s) s.textContent = sub;
    if (b) b.style.width = pct + '%';
    if (o) o.classList.add('visible');
  },
  _updateOverlay: (title, sub, pct) => {
    const t = document.getElementById('export-overlay-title');
    const s = document.getElementById('export-overlay-sub');
    const b = document.getElementById('export-overlay-bar');
    if (t && title !== undefined) t.textContent = title;
    if (s && sub   !== undefined) s.textContent = sub;
    if (b && pct   !== undefined) b.style.width = pct + '%';
  },
  _hideOverlay: () => {
    const o = document.getElementById('export-overlay');
    if (o) o.classList.remove('visible');
    const b = document.getElementById('export-overlay-bar');
    if (b) b.style.width = '0%';
  },

  // ── Toast ────────────────────────────────────────────────────────────
  _toast: (msg, type = 'success', duration = 3000) => {
    const toast = document.getElementById('export-toast');
    const msgEl = document.getElementById('export-toast-msg');
    const icon  = document.getElementById('export-toast-icon');
    if (!toast) return;
    const icons = { success: '✅', error: '❌', info: '📋' };
    toast.className = `show ${type}`;
    if (icon)  icon.textContent  = icons[type] || '✅';
    if (msgEl) msgEl.textContent = msg;
    clearTimeout(ExportEngine._toastTimer);
    ExportEngine._toastTimer = setTimeout(() => {
      if (toast.classList) toast.classList.remove('show');
    }, duration);
  },

  // ── Step A: Chart render pipeline helpers ────────────────────────────
  //
  // ROOT CAUSE OF ANNOTATION LOSS:
  // The previous code set animation = false then called chart.update('none').
  // When animation is false, Chart.js skips ALL animation hooks — including
  // onComplete. The annotation drawing function (which lives in onComplete)
  // never ran, so bars rendered without labels.
  //
  // FIX: Mutate animation.duration = 0 on the EXISTING animation object.
  // This preserves the onComplete reference while making the animation
  // complete synchronously (duration 0 = instant, fires onComplete in
  // the same call stack as chart.update()).

  /**
   * _awaitChartDraw(chart)
   * Guarantees that a chart's onComplete annotation handler has fully
   * executed before returning. Mutates animation.duration to 0 so the
   * update() fires onComplete synchronously, then restores duration.
   *
   * @param {Chart} chart — A Chart.js instance from ChartEngine.instances
   * @returns {Promise<void>} resolves after onComplete has fired
   */
  _awaitChartDraw: (chart) => {
    return new Promise((resolve) => {
      if (!chart || !chart.ctx || !chart.canvas) {
        resolve();
        return;
      }

      const anim = chart.options.animation;

      // Guard: if no animation config or no onComplete, just update and resolve
      if (!anim || typeof anim !== 'object' || typeof anim.onComplete !== 'function') {
        // Chart has no onComplete annotation — still force a clean render
        try { chart.update(); } catch (_) { /* ignore render errors during export */ }
        resolve();
        return;
      }

      // Backup the original duration (default 300ms in Chart.js 4.x)
      const savedDuration = anim.duration;
      anim._exportDurationBak = savedDuration;

      // Inject a one-time onComplete wrapper that resolves our Promise
      // and then restores original state and calls original handler
      const originalOnComplete = anim.onComplete;
      let resolved = false;

      anim.onComplete = function(context) {
        // Restore duration immediately inside the handler
        anim.duration = anim._exportDurationBak;
        delete anim._exportDurationBak;

        // Restore original onComplete
        anim.onComplete = originalOnComplete;

        // Call original annotation drawing function with correct `this` binding
        try {
          originalOnComplete.call(this, context);
        } catch (err) {
          console.warn('[ExportEngine._awaitChartDraw] onComplete error:', err);
        }

        // Log chart render to debug panel (no-op in production)
        const chartId = (chart.canvas && chart.canvas.id) ? chart.canvas.id : 'chart-unknown';
        ExportDebug.logChart(chartId, Math.round(performance.now()), true, false);

        if (!resolved) {
          resolved = true;
          resolve();
        }
      };

      // Set duration to 0 — animation completes instantly, onComplete fires now
      anim.duration = 0;

      try {
        chart.update();
      } catch (err) {
        // If update() itself throws, clean up and resolve anyway
        console.warn('[ExportEngine._awaitChartDraw] chart.update() error:', err);
        anim.duration   = anim._exportDurationBak ?? savedDuration;
        anim.onComplete = originalOnComplete;
        delete anim._exportDurationBak;
        if (!resolved) { resolved = true; resolve(); }
      }

      // Safety timeout: if onComplete never fires (e.g. chart is hidden/0-size),
      // resolve after 300ms to prevent export from hanging indefinitely
      setTimeout(() => {
        if (!resolved) {
          resolved = true;
          // Clean up in case the handler never ran
          if (anim._exportDurationBak !== undefined) {
            anim.duration   = anim._exportDurationBak;
            delete anim._exportDurationBak;
          }
          if (anim.onComplete !== originalOnComplete) {
            anim.onComplete = originalOnComplete;
          }
          // Log as timed-out (verified=false) to debug panel
          const chartId2 = (chart.canvas && chart.canvas.id) ? chart.canvas.id : 'chart-timeout';
          ExportDebug.logChart(chartId2, 300, false, true);
          resolve();
        }
      }, 300);
    });
  },

  /**
   * _verifyCanvasPaint(chart)
   * Samples 5 pixels inside a chart's data area to confirm it is not blank.
   * Returns true if the canvas has visible content, false if it appears empty.
   * Used to decide whether to retry rendering after _awaitChartDraw.
   *
   * @param {Chart} chart — A Chart.js instance
   * @returns {boolean} true = has visible content | false = appears blank
   */
  _verifyCanvasPaint: (chart) => {
    if (!chart || !chart.canvas || !chart.chartArea) return true; // can't verify, assume ok

    const canvas = chart.canvas;
    const ctx    = canvas.getContext('2d');
    if (!ctx) return true;

    const { top, left, right, bottom } = chart.chartArea;
    const w  = right  - left;
    const h  = bottom - top;

    // Skip verification if chart area is degenerate (hidden / zero-size tab)
    if (w <= 0 || h <= 0) return true;

    // Sample 5 spread points across the chart data area
    const cx = left + w / 2;
    const cy = top  + h / 2;
    const points = [
      [cx,           cy],
      [left  + w * 0.2, cy],
      [left  + w * 0.8, cy],
      [cx,           top  + h * 0.2],
      [cx,           top  + h * 0.8]
    ];

    // Scale sample coordinates for high-DPI canvases (devicePixelRatio)
    // The canvas CSS size ≠ pixel size when scale > 1
    const scaleX = canvas.width  / (canvas.offsetWidth  || canvas.width);
    const scaleY = canvas.height / (canvas.offsetHeight || canvas.height);

    let nonTransparentCount = 0;
    for (const [px, py] of points) {
      try {
        const pixel = ctx.getImageData(
          Math.round(px * scaleX),
          Math.round(py * scaleY),
          1, 1
        ).data;
        // pixel[3] is alpha — 0 = fully transparent
        if (pixel[3] > 0) nonTransparentCount++;
      } catch (_) {
        // getImageData can throw SecurityError if canvas is tainted
        return true; // assume ok, don't block export
      }
    }

    // Require at least 2 of 5 points to be non-transparent
    return nonTransparentCount >= 2;
  },

  /**
   * _prepareCharts()
   * Iterates all ChartEngine instances, runs _awaitChartDraw on each
   * concurrently (Promise.all), then verifies paint and retries once if
   * a chart appears blank.
   *
   * @returns {Promise<void>}
   */
  _prepareCharts: async () => {
    if (typeof ChartEngine === 'undefined' || !ChartEngine.instances) return;

    const charts = Object.values(ChartEngine.instances).filter(c => c && c.ctx);

    // Phase 1: draw all charts with duration=0 concurrently
    await Promise.all(charts.map(c => ExportEngine._awaitChartDraw(c)));

    // Phase 2: double requestAnimationFrame — ensures browser has flushed
    // all pending canvas compositing operations to the GPU layer
    await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));

    // Phase 2.5: additional settling delay — gives complex charts (multi-dataset,
    // annotated) extra time to finish compositing before blank-paint verification.
    // This reduces false-positive blank detections and avoids unnecessary retries.
    await new Promise(r => setTimeout(r, 200));

    // Phase 3: verify each chart has visible content; retry once if blank
    const blanks = charts.filter(c => !ExportEngine._verifyCanvasPaint(c));
    if (blanks.length > 0) {
      console.warn(`[ExportEngine] ${blanks.length} chart(s) appear blank, retrying render...`);
      await Promise.all(blanks.map(c => ExportEngine._awaitChartDraw(c)));
      // Final single rAF after retry
      await new Promise(r => requestAnimationFrame(r));
    }
  },

  // ── Pre-export preparation (hardened) ───────────────────────────────
  _prepare: async () => {
    // 1. Save scroll + scroll to top (sticky header fix)
    ExportEngine._savedScrollY = window.scrollY || 0;
    window.scrollTo(0, 0);

    // 2. Expand anomaly panel if visible — CLASS-BASED ONLY (never inline style)
    //    Save pre-export open state so _restore() returns exactly to it.
    const strip = document.getElementById('anomaly-strip');
    const panel = document.getElementById('anomaly-panel');
    ExportEngine._panelWasOpen = panel ? panel.classList.contains('open') : false;
    if (strip && strip.style.display !== 'none' && panel) {
      panel.classList.add('open');   // show via class — preserves toggle mechanism
    }

    // 3. Timing: start chart render clock
    ExportEngine._t.chartStart = performance.now();

    // 4. Guaranteed chart render pipeline (Step A)
    await ExportEngine._prepareCharts();

    // 5. Record chart render duration
    ExportEngine._t.chartEnd = performance.now();
    const chartMs = ExportEngine._t.chartEnd - ExportEngine._t.chartStart;
    ExportDebug.set('chart render', `${chartMs.toFixed(0)}ms`, chartMs > 500 ? 'warn' : 'ok');
    ExportDebug.setId('dbg-t-charts', `${chartMs.toFixed(0)}ms`);
  },

  // ── Post-export restore ──────────────────────────────────────────────
  _restore: () => {
    // Restore scroll position
    window.scrollTo(0, ExportEngine._savedScrollY || 0);
    ExportEngine._savedScrollY = 0;

    // Hard-clear body pointer-events (belt-and-suspenders — _capture finally
    // should handle this, but this catches any edge case where it didn't)
    document.body.style.pointerEvents = '';

    // Restore anomaly panel to exact pre-export state — class-based only.
    // Always remove any lingering inline style.display (belt-and-suspenders
    // against any future code path that sets it directly again).
    const panel = document.getElementById('anomaly-panel');
    if (panel) {
      panel.style.display = '';                           // clear ALL inline style.display
      if (ExportEngine._panelWasOpen) {
        panel.classList.add('open');                      // was open → keep open
      } else {
        panel.classList.remove('open');                   // was closed → restore closed
      }
      ExportEngine._panelWasOpen = undefined;
    }

    // Restore chart animation durations (Step A)
    // The _awaitChartDraw helper restores duration inside onComplete, so
    // this loop is a safety net for charts that timed out (safety timeout path).
    if (typeof ChartEngine !== 'undefined' && ChartEngine.instances) {
      Object.values(ChartEngine.instances).forEach(chart => {
        if (!chart || !chart.ctx || !chart.options.animation) return;
        const anim = chart.options.animation;
        // Clean up any leftover backup from a timed-out safety timeout path
        if (anim._exportDurationBak !== undefined) {
          anim.duration = anim._exportDurationBak;
          delete anim._exportDurationBak;
        }
      });
    }
  },

  // ── Shared onclone — full expanded version (C4 fix + C2) ────────────
  _onclone: (clonedDoc) => {
    // Remove sticky from header
    const hdr = clonedDoc.querySelector('.top-header');
    if (hdr) hdr.style.position = 'relative';

    // Expand scroll-constrained table containers
    clonedDoc.querySelectorAll('.table-wrapper').forEach(tw => {
      tw.style.maxHeight = 'none';
      tw.style.overflow  = 'visible';
    });
    clonedDoc.querySelectorAll('.cat-scroll-wrap, .cat-chart-scroll-wrap').forEach(el => {
      el.style.height    = 'auto';
      el.style.maxHeight = 'none';
      el.style.overflow  = 'visible';
    });

    // CRITICAL C4: Remove fixed 660px height from category kpi-card containers
    clonedDoc.querySelectorAll('.kpi-card').forEach(card => {
      if (card.style.height && card.style.height.includes('660px')) {
        card.style.height   = 'auto';
        card.style.overflow = 'visible';
      }
    });
    clonedDoc.querySelectorAll('[style*="height:660px"],[style*="height: 660px"]').forEach(el => {
      el.style.height   = 'auto';
      el.style.overflow = 'visible';
    });

    // Hide export UI chrome
    ['export-toolbar','export-overlay','export-toast','snapshot-watermark','snapshot-exit-btn'].forEach(id => {
      const el = clonedDoc.getElementById(id);
      if (el) el.style.display = 'none';
    });
    clonedDoc.querySelectorAll('.section-export-menu').forEach(m => m.style.display = 'none');
    clonedDoc.querySelectorAll('.section-export-btn').forEach(b => b.style.display = 'none');

    // Remove sticky from table headers
    clonedDoc.querySelectorAll('.data-table th, .cat-tbl th').forEach(th => {
      th.style.position = 'relative';
    });
  },

  // ── Core html2canvas capture (with timing + interaction lock) ──────────
  _capture: async (element, scale) => {
    if (typeof html2canvas === 'undefined') {
      throw new Error('html2canvas not loaded. Check CDN connection.');
    }
    ExportDebug.set('scale', `${scale}×`, 'info');
    // Disable dashboard interaction during capture to prevent state mutation
    // that could corrupt mid-capture renders on large datasets.
    document.body.style.pointerEvents = 'none';
    const t0 = performance.now();
    let canvas;
    try {
      canvas = await html2canvas(element, {
      scale:           scale,
      useCORS:         true,
      allowTaint:      true,
      backgroundColor: '#E8EAED',
      logging:         false,
      imageTimeout:    10000,
      onclone:         ExportEngine._onclone
    });
      const captureMs = performance.now() - t0;
      const mp = (canvas.width * canvas.height) / 1_000_000;
      ExportDebug.set('html2canvas', `${captureMs.toFixed(0)}ms`, captureMs > 5000 ? 'warn' : 'ok');
      ExportDebug.set('canvas size', `${canvas.width}×${canvas.height} (${mp.toFixed(1)}MP)`, mp > 40 ? 'warn' : 'ok');
      ExportDebug.setId('dbg-t-capture', `${captureMs.toFixed(0)}ms`);
      ExportDebug.setId('dbg-canvas-size', `${canvas.width}×${canvas.height}`);
      ExportDebug.setId('dbg-mem-est', `${(mp * 4 / 1024).toFixed(1)}MB raw`);
    } finally {
      // Always restore pointer-events — even if html2canvas throws
      document.body.style.pointerEvents = '';
    }
    return canvas;
  },

  // ── Download ─────────────────────────────────────────────────────────
  _downloadCanvas: (canvas, filename) => {
    const link = document.createElement('a');
    link.download = filename;
    link.href = canvas.toDataURL('image/png', 1.0);
    link.click();
  },

  // ── PDF multi-page builder (H3 canvas-slice fix) ─────────────────────
  _buildPDF: (canvas, isLandscape, margin) => {
    const { jsPDF } = window.jspdf;
    const pdfW = isLandscape ? 297 : 210;
    const pdfH = isLandscape ? 210 : 297;
    const imgW = pdfW - margin * 2;
    const imgH = imgW * (canvas.height / canvas.width);

    const pdf         = new jsPDF({ orientation: isLandscape ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
    const usableH     = pdfH - margin * 2 - 8;
    const mmToPxRatio = canvas.height / imgH;
    const usableHpx   = usableH * mmToPxRatio;
    const totalPages  = Math.ceil(canvas.height / usableHpx);
    const dateStr     = new Date().toLocaleDateString('id-ID');

    for (let pg = 0; pg < totalPages; pg++) {
      if (pg > 0) pdf.addPage();
      const srcY  = Math.round(pg * usableHpx);
      const srcH  = Math.min(Math.round(usableHpx), canvas.height - srcY);
      if (srcH <= 0) break;
      const sc    = document.createElement('canvas');
      sc.width    = canvas.width;
      sc.height   = srcH;
      sc.getContext('2d').drawImage(canvas, 0, srcY, canvas.width, srcH, 0, 0, canvas.width, srcH);
      const sliceHmm = srcH / mmToPxRatio;
      pdf.addImage(sc.toDataURL('image/png', 0.92), 'PNG', margin, margin, imgW, sliceHmm, '', 'FAST');
      pdf.setFontSize(7);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`Sales Control Tower by SHP v5 · ${dateStr} · Hal ${pg+1}/${totalPages}`, margin, pdfH - 4);
    }
    return pdf;
  },

  // ── FULL PNG ─────────────────────────────────────────────────────────
  fullPNG: async () => {
    if (!ExportEngine._acquireLock('fullPNG')) return;
    const t0 = performance.now();
    ExportDebug.begin('Full PNG');
    try {
      ExportEngine._showOverlay('Preparing Dashboard...', 'Rendering all sections', 20);
      const tPrep0 = performance.now();
      await ExportEngine._prepare();
      ExportDebug.setId('dbg-t-prepare', `${(performance.now()-tPrep0).toFixed(0)}ms`);

      ExportEngine._updateOverlay('Capturing...', 'This may take a moment on large datasets', 50);
      const target = document.getElementById('view-dashboard');
      const scale  = ExportEngine._safeScale(target, ExportEngine.SCALE_PNG);
      const canvas = await ExportEngine._capture(target, scale);

      ExportEngine._updateOverlay('Saving PNG...', 'Writing file', 90);
      const tSave0 = performance.now();
      ExportEngine._downloadCanvas(canvas, ExportEngine._filename('SCT_Full_Dashboard', 'png'));
      ExportDebug.setId('dbg-t-save', `${(performance.now()-tSave0).toFixed(0)}ms`);

      ExportEngine._restore();
      ExportEngine._hideOverlay();
      ExportDebug.end(performance.now() - t0);
      ExportEngine._toast('Full dashboard exported as PNG', 'success');
    } catch (err) {
      ExportEngine._failsafe(err, 'fullPNG');
    } finally {
      ExportEngine._releaseLock();
    }
  },

  // ── FULL PDF ─────────────────────────────────────────────────────────
  fullPDF: async () => {
    if (typeof window.jspdf === 'undefined' || typeof window.jspdf.jsPDF === 'undefined') {
      ExportEngine._showOverlay('Library Error', 'jsPDF not loaded — check internet connection', 0);
      setTimeout(() => ExportEngine._hideOverlay(), 2000);
      ExportEngine._toast('jsPDF library not loaded. Check internet connection.', 'error', 5000);
      return;
    }
    if (!ExportEngine._acquireLock('fullPDF')) return;
    const t0 = performance.now();
    ExportDebug.begin('Full PDF');
    try {
      ExportEngine._showOverlay('Preparing PDF...', 'Rendering dashboard', 15);
      const tPrep0 = performance.now();
      await ExportEngine._prepare();
      ExportDebug.setId('dbg-t-prepare', `${(performance.now()-tPrep0).toFixed(0)}ms`);

      ExportEngine._updateOverlay('Capturing layout...', 'Building PDF canvas', 40);
      const target = document.getElementById('view-dashboard');
      const scale  = ExportEngine._safeScale(target, ExportEngine.SCALE_PDF);
      const canvas = await ExportEngine._capture(target, scale);
      ExportEngine._updateOverlay('Building PDF...', 'Composing pages', 70);
      const pdf = ExportEngine._buildPDF(canvas, true, ExportEngine.PDF_MARGIN);
      ExportEngine._updateOverlay('Saving PDF...', 'Writing file', 95);
      const tSave0 = performance.now();
      pdf.save(ExportEngine._filename('SCT_Full_Dashboard', 'pdf'));
      ExportDebug.setId('dbg-t-save', `${(performance.now()-tSave0).toFixed(0)}ms`);

      ExportEngine._restore();
      ExportEngine._hideOverlay();
      ExportDebug.end(performance.now() - t0);
      ExportEngine._toast('Full dashboard exported as PDF', 'success');
    } catch (err) {
      ExportEngine._failsafe(err, 'fullPDF');
    } finally {
      ExportEngine._releaseLock();
    }
  },

  // ── CLIPBOARD ────────────────────────────────────────────────────────
  clipboard: async () => {
    if (!navigator.clipboard || !window.ClipboardItem) {
      ExportEngine._toast('Clipboard API not supported in this browser (requires HTTPS)', 'error');
      return;
    }
    if (!ExportEngine._acquireLock('clipboard')) return;
    try {
      ExportEngine._showOverlay('Copying to Clipboard...', 'Capturing dashboard', 40);
      await ExportEngine._prepare();
      const target = document.getElementById('view-dashboard');
      const scale  = ExportEngine._safeScale(target, ExportEngine.SCALE_PNG);
      const canvas = await ExportEngine._capture(target, scale);
      ExportEngine._updateOverlay('Copying...', 'Writing to clipboard', 80);
      // toBlob is callback-based (not a Promise). _restore/_hideOverlay/_releaseLock
      // MUST be called inside the callback — NOT in finally — to avoid releasing
      // state before the async write completes (which left overlay blocking clicks).
      canvas.toBlob(async (blob) => {
        try {
          await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]);
          ExportEngine._restore();
          ExportEngine._hideOverlay();
          ExportEngine._releaseLock();
          ExportEngine._toast('Dashboard copied to clipboard', 'info');
        } catch (e) {
          ExportEngine._restore();
          ExportEngine._hideOverlay();
          ExportEngine._releaseLock();
          ExportEngine._toast('Clipboard write failed — requires HTTPS', 'error');
        }
      }, 'image/png', 1.0);
    } catch (err) {
      // Only outer catch runs _failsafe (toBlob never ran, lock still held)
      ExportEngine._failsafe(err, 'clipboard');
      ExportEngine._releaseLock();
    }
    // NOTE: no finally here — releaseLock is inside toBlob callback above
  },

  // ── SECTION MENU TOGGLE (C6 fix: takes event as first param) ─────────
  sectionMenu: (e, btn, sectionId) => {
    if (e && e.stopPropagation) e.stopPropagation();
    const menuId = 'menu-' + sectionId;
    const menu   = document.getElementById(menuId);
    if (!menu) return;
    document.querySelectorAll('.section-export-menu.open').forEach(m => {
      if (m.id !== menuId) m.classList.remove('open');
    });
    menu.classList.toggle('open');
  },

  closeMenus: () => {
    document.querySelectorAll('.section-export-menu.open').forEach(m => m.classList.remove('open'));
  },

  // ── SECTION PNG ──────────────────────────────────────────────────────
  sectionPNG: async (sectionId) => {
    const section = document.getElementById(sectionId);
    if (!section) { ExportEngine._toast('Section not found: ' + sectionId, 'error'); return; }
    if (!ExportEngine._acquireLock('sectionPNG')) return;
    ExportDebug.begin('Section PNG: ' + sectionId);
    const t0 = performance.now();
    try {
      ExportEngine._showOverlay('Exporting Section...', 'Capturing section view', 30);
      const tPrep0 = performance.now();
      await ExportEngine._prepare();
      ExportDebug.setId('dbg-t-prepare', `${(performance.now()-tPrep0).toFixed(0)}ms`);
      // Adaptive scale: auto-picks 3×/2×/1.5× from section height
      const scale  = ExportEngine._resolveScale(section);
      const canvas = await ExportEngine._capture(section, scale);
      const prefix = `SCT_${sectionId.replace('section-','').toUpperCase()}`;
      ExportEngine._downloadCanvas(canvas, ExportEngine._filename(prefix, 'png'));
      ExportEngine._restore();
      ExportEngine._hideOverlay();
      ExportEngine._toast('Section exported as PNG', 'success');
    } catch (err) {
      ExportEngine._failsafe(err, 'sectionPNG:' + sectionId);
    } finally {
      ExportEngine._releaseLock();
    }
  },

  // ── SECTION PDF ──────────────────────────────────────────────────────
  sectionPDF: async (sectionId) => {
    if (typeof window.jspdf === 'undefined' || typeof window.jspdf.jsPDF === 'undefined') {
      ExportEngine._toast('jsPDF not loaded. Check internet connection.', 'error', 4000); return;
    }
    const section = document.getElementById(sectionId);
    if (!section) { ExportEngine._toast('Section not found: ' + sectionId, 'error'); return; }
    if (!ExportEngine._acquireLock('sectionPDF')) return;
    try {
      ExportEngine._showOverlay('Exporting Section PDF...', 'Rendering section', 30);
      await ExportEngine._prepare();
      const scale  = ExportEngine._resolveScale(section, ExportEngine.SCALE_PDF);
      const canvas = await ExportEngine._capture(section, scale);
      const isLandscape = canvas.width > canvas.height;
      const pdf    = ExportEngine._buildPDF(canvas, isLandscape, ExportEngine.PDF_MARGIN);
      const prefix = `SCT_${sectionId.replace('section-','').toUpperCase()}`;
      pdf.save(ExportEngine._filename(prefix, 'pdf'));
      ExportEngine._restore();
      ExportEngine._hideOverlay();
      ExportEngine._toast('Section exported as PDF', 'success');
    } catch (err) {
      ExportEngine._failsafe(err, 'sectionPDF:' + sectionId);
    } finally {
      ExportEngine._releaseLock();
    }
  },

  // ── SECTION CLIPBOARD ────────────────────────────────────────────────
  sectionClipboard: async (sectionId) => {
    const section = document.getElementById(sectionId);
    if (!section) { ExportEngine._toast('Section not found: ' + sectionId, 'error'); return; }
    if (!navigator.clipboard || !window.ClipboardItem) {
      ExportEngine._toast('Clipboard API not supported (requires HTTPS)', 'error'); return;
    }
    if (!ExportEngine._acquireLock('sectionClipboard')) return;
    try {
      ExportEngine._showOverlay('Copying Section...', 'Capturing section', 40);
      await ExportEngine._prepare();
      const scale  = ExportEngine._resolveScale(section);
      const canvas = await ExportEngine._capture(section, scale);
      // releaseLock inside toBlob callback — prevents race with outer finally
      canvas.toBlob(async (blob) => {
        try {
          await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]);
          ExportEngine._restore();
          ExportEngine._hideOverlay();
          ExportEngine._releaseLock();
          ExportEngine._toast('Section copied to clipboard', 'info');
        } catch (e) {
          ExportEngine._restore();
          ExportEngine._hideOverlay();
          ExportEngine._releaseLock();
          ExportEngine._toast('Clipboard write failed — requires HTTPS', 'error');
        }
      }, 'image/png', 1.0);
    } catch (err) {
      ExportEngine._failsafe(err, 'sectionClipboard:' + sectionId);
      ExportEngine._releaseLock();
    }
    // NOTE: no finally — releaseLock is inside toBlob callback
  },

  // ── WATERMARK UPDATE ─────────────────────────────────────────────────
  _updateWatermark: () => {
    const wd = document.getElementById('watermark-date');
    const wf = document.getElementById('watermark-filter');
    if (wd) {
      wd.textContent = new Date().toLocaleDateString('id-ID', {day:'numeric', month:'short', year:'numeric'});
    }
    if (wf && typeof State !== 'undefined' && State.filters && State.options) {
      const rSz = State.filters.regions    ? State.filters.regions.size    : 0;
      const pSz = State.filters.principles ? State.filters.principles.size : 0;
      const rTt = State.options.regions    ? State.options.regions.length    : 0;
      const pTt = State.options.principles ? State.options.principles.length : 0;
      const parts = [];
      if (rSz > 0 && rSz < rTt) parts.push(`${rSz} Region`);
      if (pSz > 0 && pSz < pTt) parts.push(`${pSz} Principle`);
      wf.textContent = parts.length ? parts.join(' · ') : 'ALL DATA';
    }
  },


  // ── Timing accumulator ───────────────────────────────────────────────
  // Populated during export flow; read by ExportDebug and performance log.
  _t: { prepareStart: 0, chartStart: 0, chartEnd: 0 },

  // ── Export mutex — prevents concurrent export operations ─────────────
  _acquireLock: (caller) => {
    if (ExportEngine._isExporting) {
      ExportEngine._toast('Export already in progress — please wait', 'info', 2000);
      console.warn(`[ExportEngine] Lock busy, rejecting: ${caller}`);
      return false;
    }
    ExportEngine._isExporting = true;
    ExportEngine._exportCount++;
    ExportDebug.setId('dbg-state', 'exporting…');
    ExportDebug.setId('dbg-export-num', String(ExportEngine._exportCount));
    return true;
  },

  _releaseLock: () => {
    ExportEngine._isExporting = false;
    ExportDebug.setId('dbg-state', 'idle');
  },

  // ── Fail-safe recovery ────────────────────────────────────────────────
  // Called from every catch block. Guarantees no frozen UI regardless of
  // what error occurred or at what stage.
  _failsafe: (err, context) => {
    console.error(`[ExportEngine] Error in ${context}:`, err);

    // 1. Always hide overlay and restore UI
    ExportEngine._hideOverlay();

    // 2. Always restore scroll and anomaly panel state
    ExportEngine._restore();

    // 3. Always exit snapshot mode if it was active (prevents stuck state)
    if (typeof SnapshotEngine !== 'undefined' && SnapshotEngine.isActive()) {
      SnapshotEngine.exit();
    }

    // 4. Reset export lock + clear any body pointer-events block
    ExportEngine._isExporting = false;
    document.body.style.pointerEvents = '';   // ensure no click-blocking survives error
    ExportDebug.setId('dbg-state', 'error');

    // 5. User-facing error toast with context
    const msg = err && err.message ? err.message : String(err);
    ExportEngine._toast(`Export failed (${context}): ${msg}`, 'error', 6000);

    // 6. Debug panel update
    ExportDebug.set('state', `ERROR: ${msg}`, 'err');
  },

  // ── analyzeExportQuality() — pre-export quality estimator ────────────
  // Call this before exporting to get recommendations.
  // Returns a plain object with quality metadata + recommendation.
  analyzeExportQuality: (element, requestedScale) => {
    element = element || document.getElementById('view-dashboard');
    if (!element) return null;

    const rect   = element.getBoundingClientRect();
    const scale  = requestedScale || ExportEngine._adaptiveScale(element);
    const outW   = Math.round(rect.width  * scale);
    const outH   = Math.round(rect.height * scale);
    const mp     = (outW * outH) / 1_000_000;
    const memMB  = (mp * 4 / 1024).toFixed(1);

    const isSafari    = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
    const safariRisk  = isSafari && mp > ExportEngine.SAFARI_CANVAS_MP;
    const blurRisk    = scale < 1.5;
    const memRisk     = mp > ExportEngine.MAX_CANVAS_MP;

    // Recommended mode
    let recommendation = 'section-png';
    if (mp > ExportEngine.MAX_CANVAS_MP)         recommendation = 'pdf';
    else if (rect.height < ExportEngine.HEIGHT_SMALL) recommendation = 'section-png';
    else if (rect.height < ExportEngine.HEIGHT_MEDIUM) recommendation = 'section-png';
    else recommendation = 'pdf';

    const result = {
      element:        element.id || '(unknown)',
      inputSize:      `${Math.round(rect.width)}×${Math.round(rect.height)}px`,
      outputSize:     `${outW}×${outH}px`,
      scaleFactor:    `${scale}×`,
      megapixels:     `${mp.toFixed(2)}MP`,
      memoryEstimate: `${memMB}MB raw`,
      blurRisk:       blurRisk   ? 'HIGH (scale < 1.5×)' : 'LOW',
      safariRisk:     safariRisk ? `HIGH (${mp.toFixed(1)}MP > ${ExportEngine.SAFARI_CANVAS_MP}MP limit)` : 'OK',
      memoryRisk:     memRisk    ? `HIGH (${mp.toFixed(1)}MP > ${ExportEngine.MAX_CANVAS_MP}MP limit)` : 'OK',
      recommendation,
      notes: []
    };

    if (safariRisk) result.notes.push('Use section export on Safari to avoid blank output.');
    if (blurRisk)   result.notes.push('Increase scale or use section export for sharper result.');
    if (memRisk)    result.notes.push('Full PNG may fail. Use section export or PDF instead.');
    if (!safariRisk && !blurRisk && !memRisk) result.notes.push('Export quality looks good for selected mode.');

    console.table ? console.table(result) : console.log('[ExportEngine.analyzeExportQuality]', result);
    ExportDebug.set('risk', `${result.blurRisk === 'LOW' ? 'LOW' : 'HIGH'} ${mp.toFixed(1)}MP`, blurRisk || safariRisk ? 'warn' : 'ok');
    ExportDebug.setId('dbg-risk', `${result.recommendation} (${mp.toFixed(1)}MP)`);
    return result;
  },

  // ── INITIALIZE ───────────────────────────────────────────────────────
  init: () => {
    // Close section menus on outside click
    document.addEventListener('click', (e) => {
      if (!e.target.closest('.section-export-wrap')) {
        ExportEngine.closeMenus();
      }
    });

    ExportEngine._updateWatermark();

    // M3: Validate section IDs exist in DOM
    ['section-principle-exec','section-perf','section-ca','section-ws','section-ps','section-action'].forEach(id => {
      if (!document.getElementById(id)) {
        console.warn(`[ExportEngine] Section #${id} not found. Per-section export for this section will not work.`);
      }
    });

    // CDN availability warnings
    if (typeof html2canvas === 'undefined') {
      console.warn('[ExportEngine] html2canvas not loaded. PNG export unavailable.');
    }
    if (typeof window.jspdf === 'undefined') {
      console.warn('[ExportEngine] jsPDF not loaded. PDF export unavailable.');
    }

    // Auto-activate debug panel if DEBUG_EXPORT is set before page load
    if (window.DEBUG_EXPORT === true) {
      setTimeout(() => ExportDebug.show(), 600);
    }

    // ESC key: exit snapshot mode if active
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && typeof SnapshotEngine !== 'undefined' && SnapshotEngine.isActive()) {
        e.preventDefault();
        SnapshotEngine.exit();
      }
    });
  }
};
